#!/bin/bash

# Check args
if [ "$#" -lt 2 ]; then
    echo "Usage: $0 <namespace> <resource_type>"
    exit 1
fi

#NAMESPACE=$1
#RESOURCE_TYPE=$2

# get Kubernetes resources
#kubectl get $RESOURCE_TYPE -n "$NAMESPACE" --no-headers -o custom-columns=NAME:.metadata.name,CPU:.spec.containers[*].resources.requests.cpu,MEMORY:.spec.containers[*].resources.requests.memory | awk '{print "Resource:", "'$RESOURCE_TYPE'", "Namespace:", "'$NAMESPACE'", "Name:", $1, "CPU:", $2, "Memory:", $3}'


# Define command-line arguments

NAMESPACE=$1
RESOURCE_TYPE=$2

# Retrieve resource usage statistics from Kubernetes
kubectl get $RESOURCE_TYPE -n $NAMESPACE | tail -n +2 | while read line
do
  # Extract CPU and memory usage from the output
  NAME=$(echo $line | awk '{print $1}')
  CPU=$(echo $line | awk '{print $2}')
  MEMORY=$(echo $line | awk '{print $3}')

  # Output the statistics to the console
  # "Resource, Namespace, Name, CPU, Memory"
  echo "$RESOURCE_TYPE, $NAMESPACE, $NAME, $CPU, $MEMORY"
done
    